name: example
description: Demonstrates how to use the fl_jverify plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_jverify:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_curiosity: ^3.5.0
  flutter_waya: ^1.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true