name: fl_jverify
description: Jverify plugin for flutter, only Android and IOS are supported
version: 0.0.2
repository: https://github.com/Wayaer/fl_jverify.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.fl.jverify
        pluginClass: FlJVerifyPlugin
      ios:
        pluginClass: FlJVerifyPlugin